services:
    # REST resource with defined custom controller
    eyja_rest_demo.controller.product:
        parent: eyja_rest.abstract_controller
        class: Eyja\RestDemoBundle\Controller\RestProductController
        arguments: [EyjaRestDemoBundle:Product, product]
        tags: [ { name: rest.controller } ]

    # Resource without custom controller
    eyja_rest_demo.controller.category:
        parent: eyja_rest.abstract_controller
        arguments: [EyjaRestDemoBundle:Category, category]
        tags: [ { name: rest.controller } ]
        calls:
            - [setAllowedActions, [[getCollection, getSingle]]]
            - [setAllowedFilterFields, [[name, parentId]]]
